#server:
#  port: 9001
#spring:
#  application:
#    name: tensquare-base
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.35.129:3306/tensquare_base?characterEncoding=utf-8&useSSL=false
#    username: root
#    password: 517529
#  jpa:
#    database: mysql
#    show-sql: true
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true
