server:
  port: 9006
spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      host: 192.168.35.129
      database: spitdb
      uri: mongodb://192.168.35.129/spitdb
      port: 27107
  redis:
    host: 192.168.35.129